//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TreeBuilder.rc
//
#define IDD_TREEBUILDER_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_DIALOG2                     131
#define IDD_DIALOG3                     132
#define IDC_CONVLIST                    1008
#define IDC_ADDCONV                     1009
#define IDC_DELCONV                     1010
#define IDC_SAVECONV                    1011
#define IDC_EDITCONV                    1012
#define IDC_NAME                        1013
#define IDC_TEXT                        1014
#define IDC_RADIO2                      1018
#define IDC_RADIOFLAG1                  1019
#define IDC_EDITFLAG1                   1020
#define IDC_RADIOFLAG3                  1021
#define IDC_RADIO4                      1022
#define IDC_EDITFLAG2                   1023
#define IDC_EDITATTR1                   1024
#define IDC_EDITATTR2                   1025
#define IDC_EDITVAL1                    1026
#define IDC_RADIOFLAG4                  1027
#define IDC_RADIO5                      1028
#define IDC_EDITFLAG3                   1029
#define IDC_RADIOFLAG5                  1030
#define IDC_RADIO6                      1031
#define IDC_EDITFLAG4                   1032
#define IDC_RADIOEQ1                    1033
#define IDC_RADIONEQ1                   1034
#define IDC_RADIOGT1                    1035
#define IDC_RADIOLT1                    1036
#define IDC_EDITVAL2                    1037
#define IDC_RADIOEQ2                    1038
#define IDC_RADIONEQ2                   1039
#define IDC_RADIOGT2                    1040
#define IDC_RADIOLT2                    1041
#define IDC_CONLIST1                    1044
#define IDC_ADDCON                      1045
#define IDC_DELCON                      1046
#define IDC_SPEAK                       1048
#define IDC_REPLY1                      1049
#define IDC_REPLYEXIT1                  1051
#define IDC_REPLY2                      1052
#define IDC_REPLYEXIT2                  1054
#define IDC_REPLY3                      1055
#define IDC_REPLYEXIT3                  1057
#define IDC_REPLY4                      1058
#define IDC_REPLYEXIT4                  1060
#define IDC_REPLY5                      1061
#define IDC_REPLYEXIT5                  1063
#define IDC_EDITATTR6                   1064
#define IDC_EDITVAL6                    1065
#define IDC_RADIOEQ3                    1066
#define IDC_RADIONEQ3                   1067
#define IDC_RADIOGT3                    1068
#define IDC_RADIOLT3                    1069
#define IDC_REPLY6                      1070
#define IDC_REPLYEXIT6                  1072
#define IDC_LOAD                        1073
#define IDC_SAVE                        1074
#define IDC_SCRIPT                      1075
#define IDC_CONN                        1076
#define IDC_CONAME                      1078
#define IDC_FAIL                        1079
#define IDC_REPLYCON1                   1080
#define IDC_REPLYCON2                   1081
#define IDC_REPLYCON3                   1082
#define IDC_REPLYCON4                   1083
#define IDC_REPLYCON5                   1084
#define IDC_REPLYCON6                   1085
#define IDC_SPEED                       1086
#define IDC_SOUNDFILE                   1087
#define IDC_EDITATTR7                   1088
#define IDC_EDITVAL7                    1089
#define IDC_RADIOEQ4                    1090
#define IDC_RADIONEQ4                   1091
#define IDC_RADIOGT4                    1092
#define IDC_RADIOLT4                    1093
#define IDC_SNDBUTTON                   1094
#define IDC_BACK                        1095
#define IDC_ICON1                       1096
#define IDC_SPEAKX                      1097
#define IDC_BACKBUTTON                  1098
#define IDC_ICONBUTTON                  1099
#define IDC_CUSTOM                      1099
#define IDC_SPEAKY                      1100
#define IDC_SPEAKWIDTH                  1101
#define IDC_SPEAKHEIGHT                 1102
#define IDC_SPEAKFONT                   1103
#define IDC_REPLYX                      1104
#define IDC_REPLYY                      1105
#define IDC_REPLYWIDTH                  1106
#define IDC_REPLYHEIGHT                 1107
#define IDC_REPLYFONT                   1108
#define IDC_ICONX                       1109
#define IDC_ICONY                       1110
#define IDC_RADIOFLAG2                  1130
#define IDC_RADIO3                      1131
#define IDC_EDITFLAG5                   1132
#define IDC_RADIOFLAG6                  1133
#define IDC_RADIO7                      1134
#define IDC_EDITFLAG6                   1135
#define IDC_RADIOFLAG7                  1136
#define IDC_RADIO8                      1137
#define IDC_EDITFLAG7                   1138
#define IDC_RADIOFLAG8                  1139
#define IDC_RADIO9                      1140
#define IDC_EDITFLAG8                   1141
#define IDC_EDITATTR3                   1142
#define IDC_EDITVAL3                    1143
#define IDC_EDITATTR4                   1148
#define IDC_EDITVAL4                    1149
#define IDC_EDITATTR8                   1154
#define IDC_EDITVAL8                    1155
#define IDC_EDITATTR9                   1160
#define IDC_EDITVAL9                    1161

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
